"""empty message

Revision ID: 1c52d4eec54a
Revises: edc2994bdc2a
Create Date: 2023-09-19 12:49:42.635303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c52d4eec54a'
down_revision = 'edc2994bdc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=50), nullable=False))
        batch_op.drop_column('http_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('http_method', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('ip')

    # ### end Alembic commands ###
