"""empty message

Revision ID: edc2994bdc2a
Revises: b9b2e5b1d296
Create Date: 2023-09-19 12:46:43.171640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edc2994bdc2a'
down_revision = 'b9b2e5b1d296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('end_point', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('http_method', sa.String(length=50), nullable=False))
        batch_op.drop_column('response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('http_method')
        batch_op.drop_column('end_point')
        batch_op.drop_column('time_stamp')

    # ### end Alembic commands ###
